// 100개 메뉴 + 메뉴별 개별 문구 적용
export const MENU_DATA = [
  { id: 1, name: '샐러드', heavy: false, comment: '가볍고 신선한 하루의 시작! 🥗' },
  { id: 2, name: '제육볶음', heavy: true, comment: '실패 없는 직장인 부동의 1위! 🥩' },
  { id: 3, name: '연어덮밥', heavy: false, comment: '고소한 연어가 입안에서 살살 녹아요 🍣' },
  { id: 4, name: '감자탕', heavy: true, comment: '진한 국물에 밥 한 그릇 뚝딱! 🍲' },
  { id: 5, name: '샌드위치', heavy: false, comment: '간편하지만 꽉 찬 영양 한 끼 🥪' },
  { id: 6, name: '돈까스', heavy: true, comment: '겉바속촉의 정석, 오늘은 돈까스다! 🐷' },
  { id: 7, name: '포케', heavy: false, comment: '건강하고 든든한 하와이안 서퍼식! 🥗' },
  { id: 8, name: '부대찌개', heavy: true, comment: '라면 사리 추가는 필수인 거 아시죠? 🥘' },
  { id: 9, name: '김밥', heavy: false, comment: '간단하지만 든든한 한국인의 소울푸드 🍙' },
  { id: 10, name: '삼겹살', heavy: true, comment: '낮에 먹는 고기가 진짜 맛있는 법! 🥓' },
  { id: 11, name: '메밀소바', heavy: false, comment: '시원하고 깔끔하게 한 젓가락! 🍜' },
  { id: 12, name: '찜닭', heavy: true, comment: '단짠단짠 양념에 당면까지 완벽 🍗' },
  { id: 13, name: '요거트볼', heavy: false, comment: '상큼하게 즐기는 건강한 한 끼 🥣' },
  { id: 14, name: '짜장면', heavy: true, comment: '이사 안 가도 점심엔 짜장면이죠 🥢' },
  { id: 15, name: '닭가슴살 샐러드', heavy: false, comment: '오운완! 식단까지 완벽하게 💪' },
  { id: 16, name: '순대국', heavy: true, comment: '뜨끈한 국밥 든든하게 먹고 가요 뚝배기!' },
  { id: 17, name: '유부초밥', heavy: false, comment: '귀엽고 맛있는 한 입의 행복 🦊' },
  { id: 18, name: '햄버거 세트', heavy: true, comment: '가끔은 기름진 게 당기는 법! 🍔' },
  { id: 19, name: '냉면', heavy: false, comment: '가슴속까지 뻥 뚫리는 시원함 🧊' },
  { id: 20, name: '뼈해장국', heavy: true, comment: '등뼈 발라먹는 재미가 쏠쏠해요 🦴' },
  { id: 21, name: '토스트', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 22, name: '피자', heavy: true, comment: '치즈가 듬뿍! 오늘 탄수화물 파티 🍕' },
  { id: 23, name: '비빔밥', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 24, name: '라멘', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 25, name: '죽', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 26, name: '갈비탕', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 27, name: '미역국', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 28, name: '육개장', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 29, name: '회덮밥', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 30, name: '불닭볶음면', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 31, name: '계란말이', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 32, name: '카레라이스', heavy: true, comment: '향긋한 풍미가 일품인 카레 한 그릇 🍛' },
  { id: 33, name: '생선구이', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 34, name: '삼계탕', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 35, name: '닭곰탕', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 36, name: '돼지불백', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 37, name: '샐러드 파스타', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 38, name: '짬뽕', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 39, name: '잔치국수', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 40, name: '마라탕', heavy: true, comment: '스트레스 풀리는 알싸한 매운맛! 🔥' },
  { id: 41, name: '포케볼', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 42, name: '닭갈비', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 43, name: '오트밀', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 44, name: '소고기국밥', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 45, name: '두부샐러드', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 46, name: '불고기덮밥', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 47, name: '과일볼', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 48, name: '족발', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 49, name: '콩국수', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 50, name: '치킨', heavy: true, comment: '점심 치킨은 참을 수 없지! 🍗' },
  { id: 51, name: '리코타치즈 샐러드', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 52, name: '스테이크', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 53, name: '비건볼', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 54, name: '곱창전골', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 55, name: '모밀국수', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 56, name: '양념갈비', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 57, name: '바나나 팬케이크', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 58, name: '떡볶이', heavy: true, comment: '매콤달콤 국민 간식 겸 식사! 🍡' },
  { id: 59, name: '닭죽', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 60, name: '로제파스타', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 61, name: '현미도시락', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 62, name: '크림파스타', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 63, name: '저당도시락', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 64, name: '규동', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 65, name: '두부덮밥', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 66, name: '타코 세트', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 67, name: '아보카도 샐러드', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 68, name: '케밥', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 69, name: '채소비빔밥', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 70, name: '오므라이스', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 71, name: '곤약볶음', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 72, name: '함박스테이크', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 73, name: '샤브샤브', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 74, name: '우동', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 75, name: '콜드파스타', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 76, name: '나베', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 77, name: '닭가슴살 도시락', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 78, name: '탕수육', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 79, name: '쌀국수', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 80, name: '짜글이', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 81, name: '토마토 파스타', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 82, name: '보쌈', heavy: true, comment: '야들야들한 고기와 겉절이의 만남 쌈!' },
  { id: 83, name: '채소수프', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 84, name: '김치찜', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 85, name: '현미김밥', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 86, name: '짜파구리', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 87, name: '버섯덮밥', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 88, name: '고기국수', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 89, name: '샐러드랩', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 90, name: '매운갈비찜', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 91, name: '그릭요거트', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 92, name: '차돌된장찌개', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 93, name: '야채죽', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 94, name: '닭볶음탕', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 95, name: '곤약비빔면', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 96, name: '라자냐', heavy: true, comment: '오늘은 이거닷 😍' },
  { id: 97, name: '샐러드우동', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 98, name: '치즈돈까스', heavy: true, comment: '쭉 늘어나는 치즈로 행복 충전 🧀' },
  { id: 99, name: '채식카레', heavy: false, comment: '오늘은 이거닷 😍' },
  { id: 100, name: '마제소바', heavy: true, comment: '꾸덕한 소스에 밥까지 비벼 드세요 🍜' }
];